function parameters = get_default_parameters()
%%
defaultSigmas = 4;
defaultSymmetryAngles = ((1:16)/16)*pi;
defaultSearchRange = 10:5:50;
defaultSearchAngles = [-pi/4, 0,pi/4];
defaultNumberOrLines = 5;
defaultVerbose = 1;
defaultVisualize = 0;


parameters = struct(...
    'visualize',defaultVisualize ...
    ,'verbose',defaultVerbose...
    ,'searchRange',defaultSearchRange ...
    ,'sigmas',defaultSigmas ...
    ,'numberOfLines',defaultNumberOrLines...
    ,'searchAngles',defaultSearchAngles ...
    ,'symmetryAngles',defaultSymmetryAngles ...
    );

%%
end